apiVersion: v1
kind: Pod
metadata:
  name: load-test
  namespace: tenant-a
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh"]
    resources:
      requests:
        cpu: "50m"
      limits:
        cpu: "100m"
